language: node_js
node_js:
  - '18.8.0'

dist: trusty
services:
  - mongodb

env:
  - ENVIRONMENT=testing PORT=3000

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - nohup npm run start &
  - sleep 3
  - npm run test
